version: '3'
services:
  jenkins_container:
    build: .
    ports:
      - 8080:8080
      - 50000:50000
    volumes:
      - jenkins-data:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - JENKINS_ADMIN_ID=admin
      - JENKINS_ADMIN_PASSWORD=password
      - JENKINS_OPTS=--httpPort=8080
volumes:
  jenkins-data: